#!/bin/bash

if [ -z "$MONGODB_URI" ]; then
  echo "WARN: MONGODB_URI is unset";
fi

# Provide environment variables for the cron script
env | sed 's/^\(.*\)$/export \1/g' > /tmp/.envs

# Start cron
/usr/bin/go-crond -v --allow-unprivileged /opt/backup/crontab
