#!/bin/bash

if [ -z "$MONGODB_URI" ]; then
  echo "WARN: MONGODB_URI is unset";
fi

# Provide environment variables for the cron script
env | sed 's/^\(.*\)$/export \1/g' > /root/.envs

# Star cron
/usr/sbin/cron

echo Started >> /var/log/cron.log
tail -f /var/log/cron.log
